### ISSUE TITLE
build failed: capturesDir.traverse

### ISSUE THREAD

**Issue by aa86799** [zjw-swun/AppMethodOrder#24]
//def capturesDirPath = project.getProjectDir().getParentFile().path + File.separator + "captures";
我的快照目录在project/captures;   Mac OS。  
两个task中，改成 def capturesDirPath = project.getProjectDir().path + File.separator + "captures";
运行通过

**Comment by zjw-swun** [comment]
好的，谢谢反馈，我兼容一下

**Comment by hippyk** [comment]
我的Linux还是不行

FAILURE: Build failed with an exception.

* Where:
Script 'XXX/utils.gradle' line: 7

**Comment by aa86799** [comment]
你看下实际的captures目录是哪里




stone
With the best regards.


Original Message
Sender:hippyknotifications@github.com
Recipient:zjw-swun/AppMethodOrderAppMethodOrder@noreply.github.com
Cc:stone86aa86799@163.com; Authorauthor@noreply.github.com
Date:Friday, Jun 23, 2017 19:26
Subject:Re: [zjw-swun/AppMethodOrder] build failed: capturesDir.traverse(#24)


我的Linux还是不行
FAILURE: Build failed with an exception.
Where:
 Script 'XXX/utils.gradle' line: 7

**Comment by hippyk** [comment]
@aa86799 谢谢，已经解决了
