### ISSUE TITLE
求助.

### ISSUE THREAD

**Issue by kangjinwen** [zjw-swun/AppMethodOrder#27]
1. dmtracedump 工具 加入到环境变量,怎么操作?我把graphviz已安装,环境也配置好了.
2.Method-trace-analysis.jar 导入.trace文件,分析报异常,提示:exec dmtracedump exception
这是因为环境里没配置dmtracedump吗?
3.AppOutPutMethodOrder任务执行到 capturesDir.traverse 报错.
Error:(30, 1) Execution failed for task ':AppOutPutMethodOrder'.
> D:\Demo\captures

**Comment by zjw-swun** [comment]
应该是dmtracedump  没有配置到环境变量导致的，windows环境下，你找到SDK安装目录 找到platform-tools目录，然后复制这个目录地址，右键我的电脑，高级设置，环境变量，找到path，把复制的字符串加进去，就像配置java环境变量一样

**Comment by kangjinwen** [comment]
先谢谢哈,按着操作后,jar工具,可以使用了.能成功分析.
但是在AndroidStudio中的Task还是不能成功运行.
AppOutPutMethodOrder任务执行到 capturesDir.traverse 报错.
Error:(30, 1) Execution failed for task ':AppOutPutMethodOrder'.

**Comment by zjw-swun** [comment]
是Mac系统吗 还是windows

**Comment by xingstarx** [comment]
@kangjinwen 用./gradlew AppOutPutMethodOrder 有结果吗？

**Comment by Hinatasun** [comment]
表示运行完第一步生成trace文件后，找不到AppOutputMethedOrder任务，是有什么错误吗？

**Comment by Hinatasun** [comment]
同求，执行命令 ./gradlew AppOutPutMethodOrder时出错

**Comment by Hinatasun** [comment]
![image](https://user-images.githubusercontent.com/18478774/27163415-d19f6ad0-51b9-11e7-9ede-93591146d8af.png)
