### ISSUE TITLE
不懂

### ISSUE THREAD

**Issue by wanxiasijin** [zjw-swun/AppMethodOrder#29]
832 ent   3209420 ........com.zjw.appmethodorder.MainActivity.<init> ()V	MainActivity.java
832 ent   3209438 .........com.zjw.appmethodorder.BaseActivity.<init> ()V	BaseActivity.java
<init>是什么方法，啥意思

**Comment by zjw-swun** [comment]
感觉你是不是粘贴少了点什么，格式是  线程名 ent  进入时间点  全包名.类名.方法名() 方法返回值  类名.java

**Comment by zjw-swun** [comment]
v是返回值为void

**Comment by zjw-swun** [comment]
从你贴的格式来看 少了函数名
