### ISSUE TITLE
请问能查看方法耗时么？

### ISSUE THREAD

**Issue by matrixxun** [zjw-swun/AppMethodOrder#3]
非常不错的库， 但我想查阅每个方法的耗时， 或者说只输出耗时200毫秒以上的method， 这个能支持么？

**Comment by zjw-swun** [comment]
//todo 待优化 谢谢您的反馈

**Comment by matrixxun** [comment]
期待，这样的话在做性能分析会非常有帮助

**Comment by zjw-swun** [comment]
@matrixxun  方法耗时计算方式已经添加，请查阅最新readme，第6点
