### ISSUE TITLE
captures里就只生成了一个文件

### ISSUE THREAD

**Issue by wangxuan12** [zjw-swun/AppMethodOrder#30]
![qq 20170412194034](https://cloud.githubusercontent.com/assets/26371085/24956128/c888ed78-1fb8-11e7-85e1-b647a85d6912.png)

**Comment by zjw-swun** [comment]
操作流程是？只生成一个文件是你掐表生成的，生成trace文件之后还需要执行task才行哈，或者使用小工具分析

**Comment by wangxuan12** [comment]
就是指掐了表,没有执行task,task怎么执行?双击右侧面板的 AppOutPutMethodOrder任务,没找到...能告诉一下么...

**Comment by zjw-swun** [comment]
你找右侧app 然后 other 然后 AppOutPutMethodOrder
