### ISSUE TITLE
使用求助

### ISSUE THREAD

**Issue by tu2460** [zjw-swun/AppMethodOrder#36]
window10下双击右侧面板的 AppOutPutMethodOrder任务有数据，但是再双击执行AppFilterMethodOrder任务，会得到空文件啊，过滤得到空文件在window10上，虽然也有说“(可以使用 ./gradlew AppFilterMethodOrder -P package_name=com.zjw.appmethodorder执行该任务）",这个是在Android studio下Terminal里直接输入该命令吗，可能是我太笨了，觉得文档不太详细，求助

**Comment by zjw-swun** [comment]
@tu2460 建议使用小工具
