### ISSUE TITLE
生成的txt文件为空

### ISSUE THREAD

**Issue by hippyk** [zjw-swun/AppMethodOrder#38]
两个projects一样的配置，执行 AppOutPutMethodOrder ，其中一个正常，另外一个生成的txt却为空

**Comment by hippyk** [comment]
如果说为空的那个工程名含有特殊字符的话，可输出的文件名却是正确的

**Comment by hippyk** [comment]
我把为空的那个工程的输入输出路径指向不为空的那个，结果也是正确的

**Comment by hippyk** [comment]
又发现类似问题
                        println line
                        orderFile.append(line + "\n")
console输出有内容，但是文件依然是空的

**Comment by hippyk** [comment]
it.eachLine {  

这里根本没有进来，但是极偶尔会成功一次。。。

**Comment by zjw-swun** [comment]
@hippyk 819151780我qq

**Comment by hippyk** [comment]
trace to txt 为空的问题，应该是工程路径有特殊字符，改成相对路径解决了：
baseComand = "dmtracedump  -ho " + "captures/" + it.name + " >> " +
                        "captures/" + orderFile
                        .name
