### ISSUE TITLE
TraceView耗时统计不准确的问题如何解决？

### ISSUE THREAD

**Issue by zhugogogo** [zjw-swun/AppMethodOrder#42]

**Comment by zjw-swun** [comment]
@zhugogogo 根据官方文档(https://developer.android.com/studio/profile/traceview.html) Interpreted code runs more slowly when profiling is enabled. Don't try to generate absolute timings from the profiler results (such as, "function X takes 2.5 seconds to run"). The times are only useful in relation to other profile output, so you can see if changes have made the code faster or slower relative to a previous profiling run.所知(我也用了代码在函数开头结尾用System.nanoTime()时间相减，发现，生成trace的时候确实会拖慢所以函数的执行时间，比System.nanoTime()时间相减得出的时间差的比较多)。
所以建议要相对准确的话不trace,使用System.nanoTime()时间相减得出的时间
另：819151780我qq 有兴趣的话加个好友哈
