### ISSUE TITLE
AS3.0 android monitor工具换成了android profiler

### ISSUE THREAD

**Issue by Eklett** [zjw-swun/AppMethodOrder#43]
有没有测试过还可以用吗

**Comment by zjw-swun** [comment]
可以的，一样的

**Comment by zjw-swun** [comment]
@Eklett 可以的，一样的

**Comment by Eklett** [comment]
可以用，但是android profiler找不到时钟那个按钮，用了android.os.Debug.startMethodTracing();和android.os.Debug.stopMethodTracing(); 方法生成trace文件，然后要自己从手机导出trace文件到自己创建的captures文件夹。

**Comment by zjw-swun** [comment]
@Eklett 819151780我qq，这里发不了截图，我截图给你说明

**Comment by zjw-swun** [comment]
@Eklett 项目已更新，请查看最新ReadMe
