### ISSUE TITLE
android studio 3.0 无法使用

### ISSUE THREAD

**Issue by huang3eng** [zjw-swun/AppMethodOrder#44]
无法在captures文件夹下生成对应文件

**Comment by zjw-swun** [comment]
@huang3eng android studio3.0 的trace文件 生成换地方了，且命名更改了，以我的破windows为例，C:\Users\hasee\AppData\Local\Temp\cpu_trace.trace，(mac的同学 cd /private/var/folders
 在folders 搜索cpu_trace.trace)，存在cpu_trace.trace时会新建cpu_trace1.tracecpu_trace2.trace 以此类推
希望对你有帮助

**Comment by huang3eng** [comment]
@zjw-swun 你好，请问，是将.trace文件放入Method-trace-analysis.jar中吗。Method-trace-analysis.jar只能在java 1.8环境以下运行。我的java环境是1.8

**Comment by zjw-swun** [comment]
@huang3eng 恩, java1.8也行的

**Comment by huang3eng** [comment]
@zjw-swun Method-trace-analysis这个软件要怎么打开？使用JD-GUI吗

**Comment by huang3eng** [comment]
谢谢@zjw-swun ，已经解决了，我这边JD-GUI不能使用，只能用命令 java -jar 打开那个软件

**Comment by zjw-swun** [comment]
@huang3eng 不客气

**Comment by Harlber** [comment]
@huang3eng  win下双击，mac下目前只可以命令后，readme中有写～～～
