### ISSUE TITLE
使用小工具分析cpu_trace.trace文件得到的appMethodOrderTrace.txt为空，小工具也未显示。

### ISSUE THREAD

**Issue by huang3eng** [zjw-swun/AppMethodOrder#45]

**Comment by zjw-swun** [comment]
@huang3eng 是否是使用了api26以及以上的设备，掐表生成的trace文件你可以用文本编辑器打开看是否开头带有"slow"字样，好像是掐表生成的trace文件在api26后做了修改，建议你使用monitor中DDMS面板的生成trace的工具

**Comment by liao526** [comment]
@zjw-swun 你好，我的小工具也是没任何东西显示出来，然后我手动执行dmtracedump -o 命令，返回了ERROR: not at start of version (found 'SLOW?) 。trace文件用文本打开带有"slow"字样。请问这是什么意思？谢谢。

**Comment by zjw-swun** [comment]
@liao526 这个原因我解释过了，api26以及以上的设备，掐表生成的trace文件你可以用文本编辑器打开看是否开头带有"slow"字样，好像是掐表生成的trace文件在api26后做了修改，导致dmtracedump 解析失败，建议你使用monitor中DDMS面板的生成trace的工具。

**Comment by zjw-swun** [comment]
@liao526 有空我更新一下readMe

**Comment by liao526** [comment]
@zjw-swun 谢谢！没看清楚问题。用monitor生成的trace就可以解析了

**Comment by zjw-swun** [comment]
@liao526 不客气

**Comment by zjw-swun** [comment]
@liao526 我知道了，后面record按钮默认改成了cpu profiler了，https://developer.android.google.cn/studio/profile/cpu-profiler ，不再是traceview了，好像是从studio 3.1开始改的

**Comment by lieyanxia** [comment]
@zjw-swun 你好，这个软件确实蛮好用！不过，我用这个来分析自己代码的执行顺序，好像最多只能响应几个响应事件，多了就没有显示后续的内容。比如，当我输入我的包名进行分析时，有时进行了三个点击事件，有时有四个点击事件，但执行的结果得出的逻辑执行记录基本上只能执行到360行左右，多出的点击事件，它就没有逻辑执行记录。

**Comment by zjw-swun** [comment]
@lieyanxia111 可以使用dmtracedump -o 查看带ent的行信息，可能是过滤算法写的有问题，如果dmtracedump -o 得到的ent也缺少执行逻辑，那估计是采样率的问题。

**Comment by lieyanxia** [comment]
过滤算法应该是对的。按理来讲，执行的点击事件越多，得到的trace文件应该越大。而我分别针对我的APP进行了三次，四次，五次的点击事件，发现得到的trace文件都是8M左右。对于我的APP而言，AppMethodOrder只能承担三个点击事件的量。是采样率的问题吗？有办法解决吗O_O？

**Comment by zjw-swun** [comment]
@lieyanxia111 ,如果没有自定义过采样率，我也给不出好的建议，我只能建议结合debug 断点来分析了，因为已经知道函数调用栈顺序了，再结合断点分析会更加清晰理解源码，然后关于traceview提一下，traceview在生成的时候会严重拖慢JVM执行，因为存在大量IO操作，可以试试uber的一个生成trace不卡顿的改过源码的模拟器 ，地址是https://github.com/uber/nanoscope ，然后nanoscope start 之后会产生函数调用顺序的txt，希望对您有帮助

**Comment by lieyanxia** [comment]
嗯嗯，好的！谢谢！

**Comment by lieyanxia** [comment]
我刚看了下Android Profiler 进去后可以修改采样率。因为在API26以下的文件输出大小只能是8M。我的是API21，所以我自己自定义了一个采样率，把它的文件大小设置大一点。再次输出的trace文件就是我所有的点击事件的逻辑执行操作记录！谢谢您给的启发！

**Comment by zjw-swun** [comment]
@lieyanxia111 不客气，有兴趣可以加我QQ819151780讨论一下

**Comment by imLeibniz** [comment]
> 我刚看了下Android Profiler 进去后可以修改采样率。因为在API26以下的文件输出大小只能是8M。我的是API21，所以我自己自定义了一个采样率，把它的文件大小设置大一点。再次输出的trace文件就是我所有的点击事件的逻辑执行操作记录！谢谢您给的启发！

您好，我目前在做一个应用运行时的API序列捕获，还没有查到更改输出文件大小的地方，想问一下在哪里修改呢？
