### ISSUE TITLE
无法显示Debug.startMethodTrace生成的文件

### ISSUE THREAD

**Issue by VernonLee** [zjw-swun/AppMethodOrder#46]

**Comment by zjw-swun** [comment]
查看生成的trace文件你可以用文本编辑器打开看是否开头带有"slow"字样

**Comment by VernonLee** [comment]
没有，用老gradle task成功了

**Comment by zjw-swun** [comment]
@VernonLee  readme已更新，今天一个使用mac的朋友反映了这个问题，使用mac的朋友在环境配置成功且未在studio 3.1及其以后版本使用掐表生成trace时，仍然无法生成信息，建议在idea中导入AppMethodOrderUtils.zip中源码，执行trace类的main方法

**Comment by VernonLee** [comment]
好嘞，点赞
