### ISSUE TITLE
low

### ISSUE THREAD

**Issue by nealkafuly** [zjw-swun/AppMethodOrder#48]
还是log好，可以自定义个log输出文件，然后带有计算时间戳的，很简单，你这样太麻烦了

**Comment by zjw-swun** [comment]
@nealkafuly 亲~readMe确定看了吗？ 你打个给系统的TextView 打个log看看，你在官方模拟器给系统launcher打个log看看

**Comment by zjw-swun** [comment]
@nealkafuly 不管你水平怎么样，首先我开源的目的不是为了你来说我Low的，不喜欢左上角有个✘，还专门开个issues说，您还真厉害啊

**Comment by phxnirvana** [comment]
> @nealkafuly 亲~readMe确定看了吗？ 你打个给系统的TextView 打个log看看，你在官方模拟器给系统launcher打个log看看

你可以下源码打log（滑稽.jpg

**Comment by nealkafuly** [comment]
不好意思，太直男了，是可以通过注解去准确指导每一个方法的运行时间，log确实太麻烦了，不好意思，抱歉

**Comment by nealkafuly** [comment]
可以分析文件，非常好，感恩

**Comment by nealkafuly** [comment]
确实系统的方法不能看运行时间，我错了，太年轻了，实在抱歉

**Comment by zjw-swun** [comment]
@nealkafuly 嗯，原谅你了，有兴趣可以加个微信什么的，交流一下

**Comment by zjw-swun** [comment]
@nealkafuly 表示谅解
