### ISSUE TITLE
可以适用于逆向分析三方App

### ISSUE THREAD

**Issue by bigsinger** [zjw-swun/AppMethodOrder#49]
可以适用于逆向分析三方App，但是对于一个不拥有源码的App该如何生成trace文件呢？相当于不用反编译分析apk包就可以知道某个关键函数在哪里了。

**Comment by zjw-swun** [comment]
@bigsinger 咳咳，已经有用于逆序的案例了，这块自行操作这里不做提示，本项目目的并非为了逆向而产生。

**Comment by bigsinger** [comment]
求教怎么对三方App生成trace文件呢？

**Comment by zjw-swun** [comment]
支持正向，不提倡逆向


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by bigsinger** [comment]
已搞定。  操作方法总结在这里：https://blog.csdn.net/asmcvc/article/details/103870623
有需要的朋友可以参考，感谢AppMethodOrder提供的思路。

**Comment by zjw-swun** [comment]
@bigsinger 不全考虑是否是采样率问题，以及trace start 和trace end中确保操作在此次trace记录中，另，issue关闭了哈

**Comment by bigsinger** [comment]
我是用的AndroidStudio的profile功能，选择的是全记录模式，也有漏的。
