### ISSUE TITLE
直接clone demo下来运行无效果

### ISSUE THREAD

**Issue by icespring** [zjw-swun/AppMethodOrder#5]
为什么我在点了几次activity跳转后两个输出文件都是空？traceview文件明确是有包含有包名调用的。我用的是mac，直接clone下来跑的demo，没有改过代码

**Comment by icespring** [comment]
Executing tasks: [AppOutPutMethodOrder]

Configuration on demand is an incubating feature.
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to /Users/icespring/bin/android-sdk-macosx/ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

Incremental java compilation is an incubating feature.
:app:AppOutPutMethodOrder
===== tracePath is  /Users/icespring/gitworks/AppMethodOrder/captures/com.zjw.appmethodorder_2017.03.27_18.15.trace ==========

BUILD SUCCESSFUL

**Comment by zjw-swun** [comment]
您的环境变量配置了吗，android sdk的环境变量，以及dmtracedump 的环境变量配置，双击AppOutPutMethodOrder生成内容为空的话考虑使用 ./gradlew AppOutPutMethodOrder 命令（根据本库MAC环境使用者反应貌似是studio的问题）

**Comment by icespring** [comment]
经测试2.3的Android Studio在Mac上确实有问题，由于对gradle不是特别熟悉，目前并不知道问题所在。可以后续增强一下兼容性吗？

使用wrapper确实没有问题了

**Comment by zjw-swun** [comment]
好的，谢谢您的反馈
