### ISSUE TITLE
Android studio 2.3 windows 系统 环境配置环境正确，能生成AppOutMethod方法文件，过滤后没有文件生成，检查配置的包名也是正确的？

### ISSUE THREAD

**Issue by AllenCoder** [zjw-swun/AppMethodOrder#9]

**Comment by AllenCoder** [comment]
生成的未过滤文本文件有100多M，这个是否应该再优化

**Comment by AllenCoder** [comment]
我排除生成的trace文件，确实没有我的包名运行的相关信息 ，不知道是哪里的bug

**Comment by monkeydone** [comment]
这里的包名,应该是class的包名.我遇到了类似的问题.

**Comment by zjw-swun** [comment]
@lijunjieone 能给个QQ之类的联系方式吗，谢谢您对代码的改进

**Comment by zjw-swun** [comment]
@AllenCoder 用的class 包名，100M确实夸张，应该是掐表掐了很长时间吧，这个是traceview工具生成的暂时没办法优化，未过滤文本也是有参考价值的，可以考虑出一个选项，让未过滤文本不生成

**Comment by AllenCoder** [comment]
换成app包名正常了，applicationId会找不到

**Comment by zjw-swun** [comment]
@AllenCoder 暂时只支持app包名过滤

**Comment by monkeydone** [comment]
我的qq是:147401552
你有微信吗?我的微信也是这个,
谢谢你的工程,让我学到很多东西.
